const ROOT_HEADER = document.getElementById('header')
const ROOT_SEARCH =document.getElementById('search')
const ROOT_BAG = document.getElementById('bag')
const ROOT_PRODUCTS = document.getElementById('products')
const ROOT_BAGPAGE = document.getElementById('bagPage')